spring:
  liquibase.enabled: true
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/springbooks?serverTimezone=UTC"
    username: root
    password: rostov
